### ISSUE TITLE
Rust relying party

### ISSUE THREAD

**Issue by Boscop** [portier/demo-rp#12]
It would be very useful to have an example of how to use portier in a Rust web app.

**Comment by callahad** [comment]
Agreed -- we could potentially even reuse parts of the broker's crate!

However, it seems like the Rust web app landscape is going to change pretty dramatically in the near future with the release of [Tokio](https://medium.com/@carllerche/announcing-tokio-df6bb4ddb34), which will then cause backwards incompatible API changes in Hyper, which will then effectively break all of the Rust web frameworks :) So... probably worth waiting on this one until that dust settles.

**Comment by callahad** [comment]
Speak of the devil, Tokio 0.1 was [just announced](https://tokio.rs/blog/tokio-0-1/) less than two hours after that previous comment :) So... these things are rolling

**Comment by Boscop** [comment]
It's great to see such progress for web dev in Rust. 
I'm currently writing a web app in Rust where I plan to use portier for authentication, and websockets for push notifications.

**Comment by stephank** [comment]
Just noticed this issue again. A while ago I created a Rust crate for this: [`portier`](https://docs.rs/portier). So I'll close this now. 🙂
